spring:
  datasource:
    # DB 접근. MVCC 옵션은 삭제되었다.
    # db 파일이 있는 위치로 설정해주어야 하고, h2 콘솔의 url도 같아야 한다. 필자는 h2폴더 안에 넣었음.
#    url: jdbc:h2:tcp://localhost/~/h2/jpashop
    url: jdbc:h2:mem:test # 편의를 위해 메모리 모드로 수정해둔다.
    username: sa
    password:
    # DB 커넥션과 관련된 데이터 소스 설정이 완료됨.
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 자동으로 테이블을 만들어주는 모드. 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
      ddl-auto: create
    # 하이버네이트와 관련된 특정한 프로퍼티를 사용할 수 있음.
    properties:
      hibernate:
        # System.out 에 하이버네이트 실행 SQL을 남긴다. org.hibernate.SQL을 사용할 것임.
#        show_sql: true
        format_sql: true

logging.level:
  # 모든 로그 출력은 가급적 로거를 통해 남겨야 한다.
  # logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.SQL: debug
  org.hibernate.type: trace